language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=django==1.11.5
# command to install dependencies
install:
    - pip install -r tests/requirements.txt
    - pip install $DJANGO
    - pip install coveralls
script:
    - cd tests/
    - python runtests.py
