language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=django==1.11.27
  - DJANGO=django==2.2.9
  - DJANGO=django==3.0.1

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=django==2.0.6

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.17.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

# command to install dependencies
install:
    - pip install -r tests/requirements.txt
    - pip install $DJANGO
    - pip install coveralls
script:
    - cd tests/
    - python runtests.py
